# Values for the movie-service Helm release.
# Install this file with release name "movie".

image:
  repository: seryonya/movie-service
  tag: "latest"

probe:
  enabled: true
  path: /api/v1/movies/docs

postgresql:
  enabled: true
  database: movie_db
  username: movie_db_username
  password: movie_db_password

env:
  - name: DATABASE_URI
    value: postgresql://movie_db_username:movie_db_password@movie-fastapiapp-db:5432/movie_db
  - name: CAST_SERVICE_HOST_URL
    value: http://cast-fastapiapp/api/v1/casts/
